language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - ruby-head
env:
  - "RAILS_VERSION=3.2.1"
  - "RAILS_VERSION=3.2.19"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.0.10"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.1.6"
  - "RAILS_VERSION=4.2.0.beta1"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head